### PR TITLE
extra_args argument

### LINKED ISSUE #4: Keyring as variable
Module is a great idea. I think you should also expose the keyring file as possible variable.

### PR DESCRIPTION
**Pull request by bersace**
Hi,

Thanks for `gpg_import`. It's very fine !

Here i'm maintaining a custom keyring for aptly. Thus I need to pass `--no-default-keyring --keyring trustedkeys.gpg` arguments to `gpg`.

Instead of adding more and more variables to match GPG API. I suggest to simply add `extra_args`, similar to `extra_args` argument of `pip` module. Here is the patch.

This should fix #4

### CODE REVIEW

**Comment by cpmills1975** [comment]
IMHO while adding extra_args makes it simple to change the functionality of gpg and hence the module, it doesn’t sit well with the moto of “Ansible is simple automation”. If you wanted to send command line options to the underlying command, why not just use the shell or command modules?

Perhaps support for both could be implemented? That way it sits well with those used to using the underlying command and with those (like me) keen to champion the capabilities of Ansible in what is, at present, a bash heavy environment.

**Comment by bersace** [comment]
> IMHO while adding extra_args makes it simple to change the functionality of gpg and hence the module, it doesn’t sit well with the moto of “Ansible is simple automation”.

That's a matter of interpretation. `extra_args` **is** simple. And it allow not to have Ansible and gpg_import module on my way. And actually, `extra_args` is fairly common in `pip`, `bundler`, `zypper` modules as well as `ansible_ssh extra_args`.

IIRC, the primary goal of `gpg_import` module is to make `gpg` command reliable, not to provide a YAML API to GPG CLI.

That said, if anyone wants a `keyring` argument, I'll +1 the PR.

**Comment by bersace** [comment]
@tnt any update on this ?

**Comment by bersace** [comment]
:up: @tnt ?

**Pull request closed without merging**
